// flow-typed signature: e83763e8bab826fc28d93b4aea9c6229
// flow-typed version: <<STUB>>/is-buffer_v^1.1.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-buffer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'is-buffer/test/basic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'is-buffer/index' {
  declare module.exports: $Exports<'is-buffer'>;
}
declare module 'is-buffer/index.js' {
  declare module.exports: $Exports<'is-buffer'>;
}
declare module 'is-buffer/test/basic.js' {
  declare module.exports: $Exports<'is-buffer/test/basic'>;
}
