// flow-typed signature: 40c5579ca6525ab1bd99ea619d650b57
// flow-typed version: <<STUB>>/normalize.css_v3.0.3/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
