// flow-typed signature: 51e9287ce56b1dbbf23890d4efac07e0
// flow-typed version: <<STUB>>/spectacle_v^2.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spectacle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'spectacle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spectacle/__mocks__/styleMock' {
  declare module.exports: any;
}

declare module 'spectacle/example/assets/interactive' {
  declare module.exports: any;
}

declare module 'spectacle/example/lib/index' {
  declare module.exports: any;
}

declare module 'spectacle/lib/actions/index' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/appear' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/block-quote' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/block-quote.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/cite' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/cite.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/code-pane' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/code-pane.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/code' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/code.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/component-playground' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/component-playground.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/controls' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/controls.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/deck' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/export' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/fill' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/fill.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/fit' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/fit.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/fullscreen' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/fullscreen.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/heading' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/heading.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/image' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/image.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/layout' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/layout.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/link' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/link.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/list-item' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/list-item.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/list' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/list.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/manager' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/manager.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/markdown-slides' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/markdown-slides.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/markdown' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/overview' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/presenter' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/presenter.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/progress' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/progress.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/quote' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/quote.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/s' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/s.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/slide' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/slide.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/spectacle' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/table-body' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/table-body.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/table-header-item' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/table-header-item.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/table-header' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/table-header.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/table-item' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/table-item.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/table-row' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/table-row.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/table' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/table.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/text' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/text.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/transitionable' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/transitionable.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/transitions' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/typeface' {
  declare module.exports: any;
}

declare module 'spectacle/lib/components/typeface.test' {
  declare module.exports: any;
}

declare module 'spectacle/lib/index' {
  declare module.exports: any;
}

declare module 'spectacle/lib/reducers/fragment' {
  declare module.exports: any;
}

declare module 'spectacle/lib/reducers/index' {
  declare module.exports: any;
}

declare module 'spectacle/lib/reducers/route' {
  declare module.exports: any;
}

declare module 'spectacle/lib/reducers/style' {
  declare module.exports: any;
}

declare module 'spectacle/lib/store/index' {
  declare module.exports: any;
}

declare module 'spectacle/lib/themes/default/index' {
  declare module.exports: any;
}

declare module 'spectacle/lib/themes/default/print' {
  declare module.exports: any;
}

declare module 'spectacle/lib/themes/default/screen' {
  declare module.exports: any;
}

declare module 'spectacle/lib/utils/base' {
  declare module.exports: any;
}

declare module 'spectacle/lib/utils/context' {
  declare module.exports: any;
}

declare module 'spectacle/lib/utils/controller' {
  declare module.exports: any;
}

declare module 'spectacle/lib/utils/playground.default-code' {
  declare module.exports: any;
}

declare module 'spectacle/lib/utils/preloader' {
  declare module.exports: any;
}

declare module 'spectacle/server' {
  declare module.exports: any;
}

declare module 'spectacle/webpack.config' {
  declare module.exports: any;
}

declare module 'spectacle/webpack.config.production' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spectacle/__mocks__/styleMock.js' {
  declare module.exports: $Exports<'spectacle/__mocks__/styleMock'>;
}
declare module 'spectacle/example/assets/interactive.js' {
  declare module.exports: $Exports<'spectacle/example/assets/interactive'>;
}
declare module 'spectacle/example/lib/index.js' {
  declare module.exports: $Exports<'spectacle/example/lib/index'>;
}
declare module 'spectacle/index' {
  declare module.exports: $Exports<'spectacle'>;
}
declare module 'spectacle/index.js' {
  declare module.exports: $Exports<'spectacle'>;
}
declare module 'spectacle/lib/actions/index.js' {
  declare module.exports: $Exports<'spectacle/lib/actions/index'>;
}
declare module 'spectacle/lib/components/appear.js' {
  declare module.exports: $Exports<'spectacle/lib/components/appear'>;
}
declare module 'spectacle/lib/components/block-quote.js' {
  declare module.exports: $Exports<'spectacle/lib/components/block-quote'>;
}
declare module 'spectacle/lib/components/block-quote.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/block-quote.test'>;
}
declare module 'spectacle/lib/components/cite.js' {
  declare module.exports: $Exports<'spectacle/lib/components/cite'>;
}
declare module 'spectacle/lib/components/cite.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/cite.test'>;
}
declare module 'spectacle/lib/components/code-pane.js' {
  declare module.exports: $Exports<'spectacle/lib/components/code-pane'>;
}
declare module 'spectacle/lib/components/code-pane.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/code-pane.test'>;
}
declare module 'spectacle/lib/components/code.js' {
  declare module.exports: $Exports<'spectacle/lib/components/code'>;
}
declare module 'spectacle/lib/components/code.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/code.test'>;
}
declare module 'spectacle/lib/components/component-playground.js' {
  declare module.exports: $Exports<'spectacle/lib/components/component-playground'>;
}
declare module 'spectacle/lib/components/component-playground.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/component-playground.test'>;
}
declare module 'spectacle/lib/components/controls.js' {
  declare module.exports: $Exports<'spectacle/lib/components/controls'>;
}
declare module 'spectacle/lib/components/controls.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/controls.test'>;
}
declare module 'spectacle/lib/components/deck.js' {
  declare module.exports: $Exports<'spectacle/lib/components/deck'>;
}
declare module 'spectacle/lib/components/export.js' {
  declare module.exports: $Exports<'spectacle/lib/components/export'>;
}
declare module 'spectacle/lib/components/fill.js' {
  declare module.exports: $Exports<'spectacle/lib/components/fill'>;
}
declare module 'spectacle/lib/components/fill.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/fill.test'>;
}
declare module 'spectacle/lib/components/fit.js' {
  declare module.exports: $Exports<'spectacle/lib/components/fit'>;
}
declare module 'spectacle/lib/components/fit.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/fit.test'>;
}
declare module 'spectacle/lib/components/fullscreen.js' {
  declare module.exports: $Exports<'spectacle/lib/components/fullscreen'>;
}
declare module 'spectacle/lib/components/fullscreen.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/fullscreen.test'>;
}
declare module 'spectacle/lib/components/heading.js' {
  declare module.exports: $Exports<'spectacle/lib/components/heading'>;
}
declare module 'spectacle/lib/components/heading.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/heading.test'>;
}
declare module 'spectacle/lib/components/image.js' {
  declare module.exports: $Exports<'spectacle/lib/components/image'>;
}
declare module 'spectacle/lib/components/image.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/image.test'>;
}
declare module 'spectacle/lib/components/layout.js' {
  declare module.exports: $Exports<'spectacle/lib/components/layout'>;
}
declare module 'spectacle/lib/components/layout.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/layout.test'>;
}
declare module 'spectacle/lib/components/link.js' {
  declare module.exports: $Exports<'spectacle/lib/components/link'>;
}
declare module 'spectacle/lib/components/link.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/link.test'>;
}
declare module 'spectacle/lib/components/list-item.js' {
  declare module.exports: $Exports<'spectacle/lib/components/list-item'>;
}
declare module 'spectacle/lib/components/list-item.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/list-item.test'>;
}
declare module 'spectacle/lib/components/list.js' {
  declare module.exports: $Exports<'spectacle/lib/components/list'>;
}
declare module 'spectacle/lib/components/list.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/list.test'>;
}
declare module 'spectacle/lib/components/manager.js' {
  declare module.exports: $Exports<'spectacle/lib/components/manager'>;
}
declare module 'spectacle/lib/components/manager.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/manager.test'>;
}
declare module 'spectacle/lib/components/markdown-slides.js' {
  declare module.exports: $Exports<'spectacle/lib/components/markdown-slides'>;
}
declare module 'spectacle/lib/components/markdown-slides.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/markdown-slides.test'>;
}
declare module 'spectacle/lib/components/markdown.js' {
  declare module.exports: $Exports<'spectacle/lib/components/markdown'>;
}
declare module 'spectacle/lib/components/overview.js' {
  declare module.exports: $Exports<'spectacle/lib/components/overview'>;
}
declare module 'spectacle/lib/components/presenter.js' {
  declare module.exports: $Exports<'spectacle/lib/components/presenter'>;
}
declare module 'spectacle/lib/components/presenter.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/presenter.test'>;
}
declare module 'spectacle/lib/components/progress.js' {
  declare module.exports: $Exports<'spectacle/lib/components/progress'>;
}
declare module 'spectacle/lib/components/progress.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/progress.test'>;
}
declare module 'spectacle/lib/components/quote.js' {
  declare module.exports: $Exports<'spectacle/lib/components/quote'>;
}
declare module 'spectacle/lib/components/quote.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/quote.test'>;
}
declare module 'spectacle/lib/components/s.js' {
  declare module.exports: $Exports<'spectacle/lib/components/s'>;
}
declare module 'spectacle/lib/components/s.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/s.test'>;
}
declare module 'spectacle/lib/components/slide.js' {
  declare module.exports: $Exports<'spectacle/lib/components/slide'>;
}
declare module 'spectacle/lib/components/slide.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/slide.test'>;
}
declare module 'spectacle/lib/components/spectacle.js' {
  declare module.exports: $Exports<'spectacle/lib/components/spectacle'>;
}
declare module 'spectacle/lib/components/table-body.js' {
  declare module.exports: $Exports<'spectacle/lib/components/table-body'>;
}
declare module 'spectacle/lib/components/table-body.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/table-body.test'>;
}
declare module 'spectacle/lib/components/table-header-item.js' {
  declare module.exports: $Exports<'spectacle/lib/components/table-header-item'>;
}
declare module 'spectacle/lib/components/table-header-item.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/table-header-item.test'>;
}
declare module 'spectacle/lib/components/table-header.js' {
  declare module.exports: $Exports<'spectacle/lib/components/table-header'>;
}
declare module 'spectacle/lib/components/table-header.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/table-header.test'>;
}
declare module 'spectacle/lib/components/table-item.js' {
  declare module.exports: $Exports<'spectacle/lib/components/table-item'>;
}
declare module 'spectacle/lib/components/table-item.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/table-item.test'>;
}
declare module 'spectacle/lib/components/table-row.js' {
  declare module.exports: $Exports<'spectacle/lib/components/table-row'>;
}
declare module 'spectacle/lib/components/table-row.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/table-row.test'>;
}
declare module 'spectacle/lib/components/table.js' {
  declare module.exports: $Exports<'spectacle/lib/components/table'>;
}
declare module 'spectacle/lib/components/table.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/table.test'>;
}
declare module 'spectacle/lib/components/text.js' {
  declare module.exports: $Exports<'spectacle/lib/components/text'>;
}
declare module 'spectacle/lib/components/text.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/text.test'>;
}
declare module 'spectacle/lib/components/transitionable.js' {
  declare module.exports: $Exports<'spectacle/lib/components/transitionable'>;
}
declare module 'spectacle/lib/components/transitionable.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/transitionable.test'>;
}
declare module 'spectacle/lib/components/transitions.js' {
  declare module.exports: $Exports<'spectacle/lib/components/transitions'>;
}
declare module 'spectacle/lib/components/typeface.js' {
  declare module.exports: $Exports<'spectacle/lib/components/typeface'>;
}
declare module 'spectacle/lib/components/typeface.test.js' {
  declare module.exports: $Exports<'spectacle/lib/components/typeface.test'>;
}
declare module 'spectacle/lib/index.js' {
  declare module.exports: $Exports<'spectacle/lib/index'>;
}
declare module 'spectacle/lib/reducers/fragment.js' {
  declare module.exports: $Exports<'spectacle/lib/reducers/fragment'>;
}
declare module 'spectacle/lib/reducers/index.js' {
  declare module.exports: $Exports<'spectacle/lib/reducers/index'>;
}
declare module 'spectacle/lib/reducers/route.js' {
  declare module.exports: $Exports<'spectacle/lib/reducers/route'>;
}
declare module 'spectacle/lib/reducers/style.js' {
  declare module.exports: $Exports<'spectacle/lib/reducers/style'>;
}
declare module 'spectacle/lib/store/index.js' {
  declare module.exports: $Exports<'spectacle/lib/store/index'>;
}
declare module 'spectacle/lib/themes/default/index.js' {
  declare module.exports: $Exports<'spectacle/lib/themes/default/index'>;
}
declare module 'spectacle/lib/themes/default/print.js' {
  declare module.exports: $Exports<'spectacle/lib/themes/default/print'>;
}
declare module 'spectacle/lib/themes/default/screen.js' {
  declare module.exports: $Exports<'spectacle/lib/themes/default/screen'>;
}
declare module 'spectacle/lib/utils/base.js' {
  declare module.exports: $Exports<'spectacle/lib/utils/base'>;
}
declare module 'spectacle/lib/utils/context.js' {
  declare module.exports: $Exports<'spectacle/lib/utils/context'>;
}
declare module 'spectacle/lib/utils/controller.js' {
  declare module.exports: $Exports<'spectacle/lib/utils/controller'>;
}
declare module 'spectacle/lib/utils/playground.default-code.js' {
  declare module.exports: $Exports<'spectacle/lib/utils/playground.default-code'>;
}
declare module 'spectacle/lib/utils/preloader.js' {
  declare module.exports: $Exports<'spectacle/lib/utils/preloader'>;
}
declare module 'spectacle/server.js' {
  declare module.exports: $Exports<'spectacle/server'>;
}
declare module 'spectacle/webpack.config.js' {
  declare module.exports: $Exports<'spectacle/webpack.config'>;
}
declare module 'spectacle/webpack.config.production.js' {
  declare module.exports: $Exports<'spectacle/webpack.config.production'>;
}
